### ISSUE TITLE
Source/Main.hx:85: characters 61-65 Issue

### ISSUE THREAD

**Issue by AyMarte** [TheZoroForce240/FNF-Modcharting-Tools#20]
Every time I try to export the game with each of the source files provided and I still get the same error message every time:
```
BUILDING GAME

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : For function argument 'child'

done.
Press any key to continue . . .
```

**Comment by AyMarte** [comment]
> use flixel 4.11.0

Now I got an even larger error...

[Image Since Image To Text Sucks](https://drive.google.com/file/d/1B2_dWJTzZoFWRxES4Vd9Xpf-fysa6-Lh/view?usp=sharing)

**Comment by MemeHovy** [comment]
use flixel-addons 211.0

**Comment by AyMarte** [comment]
> use flixel-addons 211.0

But I got this error

`source/modcharting/ModchartEditorState.hx:389: charatcers 123-132 : flixel.util.FlxAxes should be Float
source/modcharting/ModchartEditorState.hx:389: characters 123-132 : … For optional function argument 'ScrollX'`

**Comment by MemeHovy** [comment]
...obviously zoro needs to fix flixel 5 compatibility and crap

**Comment by MemeHovy** [comment]
actually, I might make a PR to fix it

**Comment by TheZoroForce240** [comment]
@AyMarte you need both flixel 5.2.1+ and flixel addons 3.0.0+, and in main.hx you need to remove the zoom argument from the flxgame constructor (or add a thing that checks the flixel version for it), its because it was changed with flixel updates and not all fnf engines have updated it (for example psych hasnt had a new release yet so it isnt fixed)

something like this should work
![image](https://user-images.githubusercontent.com/86524550/228763104-56308747-0d47-4b55-b25c-cea689018941.png)

**Comment by AyMarte** [comment]
> @AyMarte you need both flixel 5.2.1+ and flixel addons 3.0.0+, and in main.hx you need to remove the zoom argument from the flxgame constructor (or add a thing that checks the flixel version for it), its because it was changed with flixel updates and not all fnf engines have updated it (for example psych hasnt had a new release yet so it isnt fixed)
> 
> something like this should work ![image](https://user-images.githubusercontent.com/86524550/228763104-56308747-0d47-4b55-b25c-cea689018941.png)

I still got the same issue before: 
`source/modcharting/ModchartEditorState.hx:389: charatcers 123-132 : flixel.util.FlxAxes should be Float
source/modcharting/ModchartEditorState.hx:389: characters 123-132 : … For optional function argument 'ScrollX`

**Comment by AyMarte** [comment]
> _@AyMarte you need both flixel 5.2.1+ and flixel addons 3.0.0+, and in main.hx you need to remove the zoom argument from the flxgame constructor (or add a thing that checks the flixel version for it), its because it was changed with flixel updates and not all fnf engines have updated it (for example psych hasnt had a new release yet so it isnt fixed)
> 
> something like this should work ![image](https://user-images.githubusercontent.com/86524550/228763104-56308747-0d47-4b55-b25c-cea689018941.png)_
> I still got the same issue before:
> `source/modcharting/ModchartEditorState.hx:389: charatcers 123-132 : flixel.util.FlxAxes should be Float `
> `source/modcharting/ModchartEditorState.hx:389: characters 123-132 : … For optional function argument 'ScrollX`

Does anyone know what I could put for _float_?

**Comment by UncertainProd** [comment]
Can you maybe double-check if you have the right versions installed, by typing `haxelib list` ?
