### ISSUE TITLE
Change Mania on psych engine extra keys (with the modcharting tools) is bugged

### ISSUE THREAD

**Issue by Rorutop** [TheZoroForce240/FNF-Modcharting-Tools#22]
Recently I got a commission from someone, and it had a part where it had 5 keys changing from 4 keys. The guy compiled tposejank's psych extra keys with FNF Modcharting Tools combined, I'm surprised the modchart tools worked with it! The only problem is changing mania is bugged, where the strum position incorrectly and sustain being mixed up. How would I fix this by coding the modchart source manually?

![image](https://user-images.githubusercontent.com/66291382/230313118-5a6488c3-99dd-476d-ab10-da79ba1594dc.png)
![image](https://user-images.githubusercontent.com/66291382/230313077-7746ada6-6306-42b8-85f5-d88ef60fca27.png)

**Comment by Vortex2Oblivion** [comment]
i think you need to re add the playfield renderer when you change keys

**Comment by Rorutop** [comment]
Do you have to remove playfieldRenderer first?

**Comment by Rorutop** [comment]
Nevermind worked.
