### ISSUE TITLE
How to open the "ModchartEditorState"? (not really an issue)

### ISSUE THREAD

**Issue by ZSolar1** [TheZoroForce240/FNF-Modcharting-Tools#29]
1. sorry for opening all of these issues. 2. can I open this state? it seems helpful

**Comment by Vortex2Oblivion** [comment]
add some code to switch to the state

**Comment by EdwhakKB** [comment]
First you need add this in "clientPrefs.hx"
`'debug_3'		=> [SIX, NONE]`
(you can change the six for something else if you want

now you need add this in "controlsSubstate.hx" (optional)

`['Key 3', 'debug_3']`

add this code in "Playstate.hx "to make the editor work (in Update function under the chart editor)


```
private var debugKeysModchart:Array<FlxKey>; //add this after the debugKeysCharacter but before KeysArray

debugKeysModchart = ClientPrefs.copyKey(ClientPrefs.keyBinds.get('debug_3')); // add this onCreate after the debugKeysCharacter and before pauseSubstate

if (FlxG.keys.anyJustPressed(debugKeysModchart) && !endingSong && !inCutscene)
			{
				persistentUpdate = false;
				paused = true;
				cancelMusicFadeTween();
				MusicBeatState.switchState(new modcharting.ModchartEditorState());
				chartingMode = true;
		
				#if desktop
				DiscordClient.changePresence("Modchart Editor", null, null, true);
				#end
			}
```

if your game compiles you are good to go

**Comment by ZSolarDev** [comment]
thank you!

**Comment by ZSolarDev** [comment]
I forgot to close this
