### ISSUE TITLE
Lua modcharts dont work on leather

### ISSUE THREAD

**Issue by Vortex2Oblivion** [TheZoroForce240/FNF-Modcharting-Tools#33]
https://streamable.com/hg732r

used to work fine, broken now

**Comment by TheZoroForce240** [comment]
i dont think i ever setup lua functions for leather so im guessing you got custom ones, i had to add a fix into the "startMod" function to reconstruct the mod table after running it so just make sure you got that added i guess

**Comment by Vortex2Oblivion** [comment]
alr ill try updating my lua functions

**Comment by Vortex2Oblivion** [comment]
ok that seemed to fix it
thanks
