### ISSUE TITLE
New update broke the multiple playfields

### ISSUE THREAD

**Issue by Rorutop** [TheZoroForce240/FNF-Modcharting-Tools#37]
Recently installed the new update of modcharting tools and made some setsubmod fixes because Zoro forgot about it. Before that the playfield strums just works fine, but now when I enter the song with that multiple playfield, the second playfield strums just sit still there and doesn't follow the all (-1) modifiers. I tried the other song and the playfield does follow the modifiers somehow. Does anyone know why the hell is this happening?

![image](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/assets/66291382/15f4b937-899a-496d-8317-e2993ece4a6b)
![image](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/assets/66291382/191263a4-659b-4385-bcd0-d73c28f12e04)
- modchart code by An Ammar

**Comment by Hiho2950** [comment]
Pls link or upload lua script

**Comment by Rorutop** [comment]
Nevermind, I just put the addPlayfield on the first line of initMods.
![image](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/assets/66291382/d329fbae-2e71-4b42-b4c8-ffd74f6a7cbb)

AND NO dumdum im not gonna give you the script stfup
