### ISSUE TITLE
Question about modchart editor

### ISSUE THREAD

**Issue by Hiho2950** [TheZoroForce240/FNF-Modcharting-Tools#38]
How can I remove an event I have add?

**Comment by EdwhakKB** [comment]
Hello there are 2 ways to do it

first way its go to the Json and search for the event and delete it (ofc this one its bad since yeah its boring and annoying)

other way is this one inside the code

if (FlxG.keys.justPressed.DELETE)

if you don't know what delete key is then change it to

if (FlxG.keys.justPressed.BACKSPACE)

(you must have selected the event first)

**Comment by Hiho2950** [comment]
> Hello there are 2 ways to do it
> 
> first way its go to the Json and search for the event and delete it (ofc this one its bad since yeah its boring and annoying)
> 
> other way is this one inside the code
> 
> if (FlxG.keys.justPressed.DELETE)
> 
> if you don't know what delete key is then change it to
> 
> if (FlxG.keys.justPressed.BACKSPACE)
> 
> (you must have selected the event first)

i wanna delete it from the editor and there is an error when i change ease to set everything be broken so i cant add another modchart event unless when i reset the editor after saving the file

**Comment by EdwhakKB** [comment]
> > Hello there are 2 ways to do it
> > first way its go to the Json and search for the event and delete it (ofc this one its bad since yeah its boring and annoying)
> > other way is this one inside the code
> > if (FlxG.keys.justPressed.DELETE)
> > if you don't know what delete key is then change it to
> > if (FlxG.keys.justPressed.BACKSPACE)
> > (you must have selected the event first)
> 
> i wanna delete it from the editor and there is an error when i change ease to set everything be broken so i cant add another modchart event unless when i reset the editor after saving the file

well basically this happen due Zoro didn't fixed yet the switch from Ease to Set, i recommend don't use any set in the editor for now (instead use, ease time "0" to do a set)

**Comment by Hiho2950** [comment]
> > > Hello there are 2 ways to do it
> > > first way its go to the Json and search for the event and delete it (ofc this one its bad since yeah its boring and annoying)
> > > other way is this one inside the code
> > > if (FlxG.keys.justPressed.DELETE)
> > > if you don't know what delete key is then change it to
> > > if (FlxG.keys.justPressed.BACKSPACE)
> > > (you must have selected the event first)
> > 
> > 
> > i wanna delete it from the editor and there is an error when i change ease to set everything be broken so i cant add another modchart event unless when i reset the editor after saving the file
> 
> well basically this happen due Zoro didn't fixed yet the switch from Ease to Set, i recommend don't use any set in the editor for now (instead use, ease time "0" to do a set)

ok thanks
