### ISSUE TITLE
An error while compiling

### ISSUE THREAD

**Issue by ZSolarDev** [TheZoroForce240/FNF-Modcharting-Tools#39]
Im trying to compile, but i get this error: C:/haxelib/fnf-modcharting-tools/git/source/modcharting/PlayfieldRenderer.hx:375: characters 21-38 : flixel.FlxStrip has no field constructVertices

I assume thats due to my flixel version, but i dont know what version i should use instead if this is the problem.

**Comment by EdwhakKB** [comment]
well that issue can happen with 2 cases

first one its that you have old modcharting tools update and FlxStrip its not added to note.hx 

second one its your flixel version but thats a very very small chance

can i see what version you got?

**Comment by ZSolarDev** [comment]
my flixel version is 5.2.0

**Comment by ZSolarDev** [comment]
btw i just updated to the latest version of flixel but the error still shows

**Comment by EdwhakKB** [comment]
check if you have right "note.hx"

**Comment by ZSolarDev** [comment]
I found out i put the old incorrect code in note.hx. thanks!
