### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Miskept** [TheZoroForce240/FNF-Modcharting-Tools#40]
I haven't used this tool in quite a bit and my dumbass forgot most stuff

How do I use a modifier with an subvalue?

**Comment by moxie-coder** [comment]
you can use `setSubMod` or `tweenModifierSubValue`

**Comment by Miskept** [comment]
> you can use `setSubMod` or `tweenModifierSubValue`

Can you give an example, my memory is very fuzzy

**Comment by moxie-coder** [comment]
`tweenModifierSubValue('modifier','subValue',val,time,'ease')`

**Comment by Miskept** [comment]
> `tweenModifierSubValue('modifier','subValue',val,time,'ease')`

Got it working but I would like the modifier to work during a certain part of the song Example: beat 100, how would I do that?

**Comment by moxie-coder** [comment]
you can use `onBeatHit(curBeat)` in your lua script

**Comment by EdwhakKB** [comment]
> > `tweenModifierSubValue('modifier','subValue',val,time,'ease')`
> 
> Got it working but I would like the modifier to work during a certain part of the song Example: beat 100, how would I do that?

there are 2 ways

the easy one:
`onBeatHit(curbeat)`

or the inCode one
`ease(beat,time,ease,modifier:subValue)`

**Comment by Miskept** [comment]
> > > `tweenModifierSubValue('modifier','subValue',val,time,'ease')`
> > 
> > 
> > Got it working but I would like the modifier to work during a certain part of the song Example: beat 100, how would I do that?
> 
> there are 2 ways
> 
> the easy one: `onBeatHit(curbeat)`
> 
> or the inCode one `ease(beat,time,ease,modifier:subValue)`

Okay that got me to remember now, thank you!
