### ISSUE TITLE
issues on psych 0.7

### ISSUE THREAD

**Issue by roma-perec-bp** [TheZoroForce240/FNF-Modcharting-Tools#42]
hscript, lua and new organized folders stuff are making compile errors

**Comment by Vortex2Oblivion** [comment]
*proceeds not to show errors*

**Comment by EdwhakKB** [comment]
you should just change the load folders, its not that hard but basically
it breaks the whole mod (since everything its on a folder now, the modcharting tools load it like it was not in folder so that means it will bug lol)

**Comment by roma-perec-bp** [comment]
> you should just change the load folders, its not that hard but basically it breaks the whole mod (since everything its on a folder now, the modcharting tools load it like it was not in folder so that means it will bug lol)

I changed imports already but there is another problem, since funkinlua and hscripts are now separated, it giving errors in modchartFunc.hx

**Comment by roma-perec-bp** [comment]
> > you should just change the load folders, its not that hard but basically it breaks the whole mod (since everything its on a folder now, the modcharting tools load it like it was not in folder so that means it will bug lol)
> 
> I changed imports already but there is another problem, since funkinlua and hscripts are now separated, it giving errors in modchartFunc.hx

It smth with variable and function stuff
