### ISSUE TITLE
how to fix this in cmd?

### ISSUE THREAD

**Issue by phrGithubGamerBR** [TheZoroForce240/FNF-Modcharting-Tools#45]
C:\Users\?\Desktop\FNF-PsychEngine-0.7.1h>haxelib git fnf-modcharting-tools https://github.com/TheZoroForce240/FNF-Modcharting-Tools

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

You already have fnf-modcharting-tools version git installed.
Updating fnf-modcharting-tools version git ...
info: please complete authentication in your browser...
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

**Comment by EdwhakKB** [comment]
there are 2 ways to do that easily
first of all modcharting tools don't work in 0.7.1 yet, so its needed use a fix (i got one for 0.7.0 tho) 
dowloand the file manually and paste it inside your source

**Comment by pablowolfgamerbr** [comment]
> existem 2 maneiras de fazer isso facilmente primeiro de todas as ferramentas de modcharting não funcionam em 0.7.1 ainda, então é necessário usar uma correção (eu tenho uma para 0.7.0 tho) baixe o arquivo manualmente e cole-o dentro de sua fonte

**Comment by phrGithubGamerBR** [comment]
it wasn't like that

**Comment by phrGithubGamerBR** [comment]
I closed the problem yes want
