### ISSUE TITLE
Base Game Support Issues

### ISSUE THREAD

**Issue by ZSolarDev** [TheZoroForce240/FNF-Modcharting-Tools#49]
### I'm trying to make base game support work, I'm making an fnf engine.

I'm working on an fnf engine called "Definitive Engine". I'm trying to add modchart support, although it's not really working. I made custom hscript functionality, although its not effecting the arrows, and It's not throwing errors. I made sure my hscript works my tracing, it works. when it throws errors it traces them, i tested this by making a null object ref and it worked. In fact, I was so desperate, that I even tried adding lua functionality. I made sure it works by printing into the console, and when it throws errors i trace it. I also tested and the errors work with lua too. I made sure the playfields were working, they were working. This was my hscript:
```haxe
function create()
{
    modchartTools = true;
}

function songStarted()
{
    trace('yoo');
    ModchartFuncs.startMod('zPF1', 'ZModifier', '', 1);
    ModchartFuncs.startMod('tipsyPF1', 'TipsyYModifier', '', 1);
    ModchartFuncs.ease(2, 4, 'cubeInOut', '
        -300, zPF1,
        1, tipsyPF1,
        2, tipsyPF1:speed
    ');
}
```
This was my lua:
```lua
function songStarted()
    print('test')
    startMod('zPF1', 'ZModifier', '', 1)
    startMod('tipsyPF1', 'TipsyYModifier', '', 1)

    ease(2, 4, 'cubeInOut', [[
        -300, zPF1,
        1, tipsyPF1,
        2, tipsyPF1:speed
    ]])
end
```
In fact I just tried using the source code to run the modcharts and i did it at the end of the startSong function, I ran this code:
```haxe
ModchartFuncs.startMod('zPF1', 'ZModifier', '', -1, instance);
ModchartFuncs.startMod('tipsyPF1', 'TipsyYModifier', '', -1, instance);
ModchartFuncs.ease(2, 4, 'cubeInOut', '
	-300, zPF1,
	1, tipsyPF1,
	2, tipsyPF1:speed
');
```
Someone, anyone, please help if you can!

**Comment by EdwhakKB** [comment]
well base game has no lua support so you might add it as first, second well it can be you didn't specify the engine (even if it doesn't have custom own variables for vanilla game i recommend use that to avoid issues with moving arrows)

**Comment by ZSolarDev** [comment]
I dont think i mentions I added lua support. also the engine is custom, what details of the engine do you need?

**Comment by ZSolarDev** [comment]
Also can you elaborate further on what you mean by "even if it doesn't have custom own variables for vanilla game i recommend use that to avoid issues with moving arrows"?

**Comment by EdwhakKB** [comment]
1. i need check if you added lua support for the mod and things, else it won't work
2. i say that since it can bug sometimes if you don't add that at project.xml so its just to avoid bugs

**Comment by ZSolarDev** [comment]
ah ok. Well do you know how i can fix the modchart tools not moving the playfields? bc its definetly using the new renderer as I can tell from the hold notes.

**Comment by EdwhakKB** [comment]
Not moving the playfields?, you added good the modifier like
ModName,modifier,specif(player,op,both),playfield
?
rememeber you need add right the modifier or else it won't work

**Comment by ZSolarDev** [comment]
You can check the code i made in the main message...

**Comment by EdwhakKB** [comment]
OH THATS WHY
Lua functions does nothing inside source, you must use modchart editor json and stuff to make it work

**Comment by ZSolarDev** [comment]
can you elaborate on the part where you said "you must use modchart editor json and stuff to make it work" further please? also im using too hscript and not just lua

**Comment by EdwhakKB** [comment]
I mean, the lua functions only works in lua ofc, but you must use editor to make the modchart inside source, otherwise Hscript and others won't load lua vars

**Comment by ZSolarDev** [comment]
oh ok. Well do you know why its not moving even when i use source code? because i showed the code i was using for source, that wasnt working.

**Comment by EdwhakKB** [comment]
maybe it can be main game issues, since well it wasn't really tested on main game so there was a chance of that way of mods (script mods) not working, editor should work tho

**Comment by ZSolarDev** [comment]
i added script loading functionality with a few lines of code and it works on psych. i changed some code to make it work for my custom engine, mostly the base game rn, and it doesnt load. also im testing with a modchart i made with the modchart editor in psych

**Comment by EdwhakKB** [comment]
Does modchart editor work?

**Comment by ZSolarDev** [comment]
hah, not in base game but in psych yes

**Comment by EdwhakKB** [comment]
hmmmm, must be MT issue i'll see what can i do

**Comment by ZSolarDev** [comment]
@EdwhakKB how is fixing it going?

**Comment by EdwhakKB** [comment]
Well for now i focused on 0.7 support and rework inside my fork, hopefully i'll fix stuff in main game next week

**Comment by ZSolarDev** [comment]
oh, ok. good luck! also, what time zone do you live in? bc if you have discord and we both are able to talk because we are awake at the same hour, then i think we can get this problem solved faster because we could have a more speedy conversation. my time zone is EST (eastern time), and the sending of this message is 9:48 PM. wbu?

**Comment by ZSolar1** [comment]
also, what time zone do you live in? bc if you have discord and we both are able to talk because we are awake at the same hour, then i think we can get this problem solved faster because we could have a more speedy conversation. my time zone is EST (eastern time), and the sending of this message is 9:48 PM. wbu?

**Comment by ZSolarDev** [comment]
HOLY

**Comment by ZSolarDev** [comment]
YESS

**Comment by ZSolarDev** [comment]
HOLY, YES! I GOT IT TO WORK BECAUSE I FORGOT A SINGLE LINE OF CODE. PLEASE, PLEASE, PLEASE, I BEG YOU TO FORGIVE ME FOR WASTING YOUR TIME. (I forgot to reconstruct the modifier table(A SINGLE LINE OF CODE), because i noticed theZeroForce240 did that in ModchartFuncs when setting up lua.)

**Comment by EdwhakKB** [comment]
oh bro 💀 
its no problem tho
i can try implement a way to explain all engines working in my fork
and also here is same hour as you but -1

Discord is @edwhak_kb

**Comment by ZSolarDev** [comment]
alright, thanks dude! also, make sure in your fork, the steps to install in the base game is also to change/add some variables bc i had to add instance to get it to work and set some private vars to public, I forgot which though.
