### ISSUE TITLE
Modchart Editor Issue

### ISSUE THREAD

**Issue by ZSolarDev** [TheZoroForce240/FNF-Modcharting-Tools#50]
Im trying to use the modchart editor, but the song doesnt play. when i mute then unmute the inst, the main menu music is treated at the inst. I'm using psych 0.6.3, please help!

**Comment by EdwhakKB** [comment]
Modchart editor need load the Playstate song, so if you try open the editor in countdown it won't work, usually do it after 1-2 seconds after song started to avoid bugs, might fix that in MT-EEdition

**Comment by ZSolarDev** [comment]
oh, thanks!
