### ISSUE TITLE
How can I load modcharts made with the modchart editor? (Psych 0.6.3)

### ISSUE THREAD

**Issue by ZSolarDev** [TheZoroForce240/FNF-Modcharting-Tools#51]
The title is very self explanatory. it exports a modchart.json and idk how to load it bc its not loading by default. (btw i mean in the actual song itself, not the editor.)

**Comment by ZSolarDev** [comment]
nvm I just edited some playfield renderer code and it works now

**Comment by MightyTheArmiddilo** [comment]
> nvm I just edited some playfield renderer code and it works now

What did you edit to fix it? I'm having the same problem.
