### ISSUE TITLE
not a bug but where do i put the codes at?

### ISSUE THREAD

**Issue by lolfuy22** [TheZoroForce240/FNF-Modcharting-Tools#52]
I'm trying to make this work but where in what lines do I put the additional codes at?

**Comment by EdwhakKB** [comment]
The readme, in the readme is all of the tutorial about how to add the modcharting tools code, usually this version works only in 0.6.3 so if you need 0.7.x use my fork instead

**Comment by lolfuy22** [comment]
ill try it

**Comment by EdwhakKB** [comment]
you can tell me any issue at this discord
@edwhak_kb im online almost 24/7

**Comment by lolfuy22** [comment]
source/states/PlayState.hx:957: characters 4-16 : Bool should be Void
source/states/PlayState.hx:988: characters 5-16 : Bool should be Void
source/states/PlayState.hx:993: characters 5-16 : Bool should be Void
source/states/PlayState.hx:1056: characters 3-14 : Bool should be Void
source/modcharting/ModchartFuncs.hx:45: characters 13-19 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:47: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:47: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:52: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:52: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:55: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:55: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:58: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:58: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:61: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:61: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:64: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:64: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:67: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:67: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:70: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:70: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:73: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:73: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:76: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:76: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:79: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:79: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:82: characters 37-43 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:82: characters 37-43 : ... For function argument 'l'
source/modcharting/ModchartFuncs.hx:87: characters 35-41 : Unknown identifier : funkin
source/modcharting/ModchartFuncs.hx:87: characters 35-41 : ... For function argument 'funkin'
source/psychlua/FunkinLua.hx:1461: characters 34-38 : Too many arguments
source/backend/BaseStage.hx:141: characters 93-105 : Bool should be Void

omfg

**Comment by EdwhakKB** [comment]
did you specify the engine ver? in project

**Comment by lolfuy22** [comment]
0.7.1h

**Comment by EdwhakKB** [comment]
you should have put it as "PSYCHVERSION == 0.7"
if it still bugs tell me

**Comment by lolfuy22** [comment]
in where?

**Comment by EdwhakKB** [comment]
project.xml

**Comment by lolfuy22** [comment]
ok i got rid of <define name="PSYCH" /> and left <define name="PSYCHVERSION" value="0.7"/> intact
then i got
source/modcharting/Modifier.hx:16: characters 8-17 : Type not found : PlayState
source/modcharting/Modifier.hx:17: characters 8-12 : Type not found : Note
source/modcharting/PlayfieldRenderer.hx:33: characters 8-17 : Type not found : PlayState
source/modcharting/PlayfieldRenderer.hx:34: characters 8-12 : Type not found : Note
source/modcharting/PlayfieldRenderer.hx:35: characters 8-17 : Type not found : StrumNote
source/modcharting/NoteMovement.hx:15: characters 8-17 : Type not found : PlayState
source/modcharting/NoteMovement.hx:16: characters 8-12 : Type not found : Note
source/modcharting/ModchartUtil.hx:18: characters 8-17 : Type not found : PlayState
source/modcharting/ModchartUtil.hx:19: characters 8-12 : Type not found : Note
source/modcharting/ModchartUtil.hx:20: characters 8-17 : Type not found : StrumNote
source/modcharting/SustainStrip.hx:10: characters 8-12 : Type not found : Note
source/modcharting/SustainStrip.hx:29: characters 24-28 : Type not found : Note

**Comment by EdwhakKB** [comment]
hmmmmm
did you added also "#PSYCH" ?

**Comment by lolfuy22** [comment]
no
where do i add it? its hard for me to know where to add it in what line

**Comment by EdwhakKB** [comment]
again project

**Comment by lolfuy22** [comment]
at what line do i put #PSYCH at?
