### ISSUE TITLE
Problem №2

### ISSUE THREAD

**Issue by TrigJop** [TheZoroForce240/FNF-Modcharting-Tools#54]
CMD does not see the installed haxelib "fnf-modcharting-tools"

**Comment by EdwhakKB** [comment]
there is a simple fix
you should add this (this is my fork that have some new modifiers and stuff ig)

`haxelib git fnf-modcharting-tools https://github.com/EdwhakKB/FNF-Modcharting-Tools`

**Comment by TrigJop** [comment]
> there is a simple fix you should add this (this is my fork that have some new modifiers and stuff ig)
> 
> `haxelib git fnf-modcharting-tools https://github.com/EdwhakKB/FNF-Modcharting-Tools`

It didn't work

**Comment by TrigJop** [comment]
> > there is a simple fix you should add this (this is my fork that have some new modifiers and stuff ig)
> > `haxelib git fnf-modcharting-tools https://github.com/EdwhakKB/FNF-Modcharting-Tools`
> 
> It didn't work

bruh now it's working and shows an error 
![image](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/assets/57638063/d882e2e3-eb21-420d-a994-30720550c566)

**Comment by Vortex2Oblivion** [comment]
> there is a simple fix
> 
> you should add this (this is my fork that have some new modifiers and stuff ig)
> 
> 
> 
> `haxelib git fnf-modcharting-tools https://github.com/EdwhakKB/FNF-Modcharting-Tools`

Shameless self promo :trollface:

**Comment by EdwhakKB** [comment]
> > there is a simple fix
> > you should add this (this is my fork that have some new modifiers and stuff ig)
> > `haxelib git fnf-modcharting-tools https://github.com/EdwhakKB/FNF-Modcharting-Tools`
> 
> Shameless self promo :trollface:

shut

**Comment by ZSolarDev** [comment]
> CMD does not see the installed haxelib "fnf-modcharting-tools"

Go to where you install all of your haxe libraries. go into fnf-modcharting-tools/source and copy paste the modcharting folder to your psych source code and try again
