### ISSUE TITLE
suggestion: make this into a haxelib

### ISSUE THREAD

**Issue by Leather128** [TheZoroForce240/FNF-Modcharting-Tools#6]
ok so i was thinking of making this like a built-in feature to leather engine since it seemed so cool, my only issue is that i *can't* use it as a haxelib because of everything being in the `source` folder and stuff. and if i'm not using it as a haxelib then i would have to manually update it in my own source which sounds like it'll be kinda painful.

**Comment by TheZoroForce240** [comment]
yea maybe i could try that, i hadnt done it before because i originally needed edited flixel files which idk if that would work with a haxelib

**Comment by Leather128** [comment]
it probably could still work, i'd at least give it a shot y'know

**Comment by Leather128** [comment]
seems like it did happen so yipee i close issue ig for now (at least you can haxelib git it now and it work :D )
