### ISSUE TITLE
Problem with compiling.

### ISSUE THREAD

**Issue by MightyTheArmiddilo** [TheZoroForce240/FNF-Modcharting-Tools#61]
When I compile, I get these two lines:

source/modcharting/ModchartEditorState.hx:393: characters 123-132 : flixel.util.FlxAxes should be Float
source/modcharting/ModchartEditorState.hx:393: characters 123-132 : ... For optional function argument 'ScrollX'

Can I get some help please? Thanks.

**Comment by EdwhakKB** [comment]
Update your Flixel-Util versions

**Comment by MightyTheArmiddilo** [comment]
> Update your Flixel-Util versions

Error: Failed with error: No such Project : flixel-util
