### ISSUE TITLE
BUG WHILE INSTALL

### ISSUE THREAD

**Issue by F1mpo** [TheZoroForce240/FNF-Modcharting-Tools#73]
help! how to fix this bug
![bug](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/assets/175312707/088b6a31-6449-4916-ba3b-be00f4d1520b)

**Comment by EdwhakKB** [comment]
Most probable thing its that your "PATH" don't have the ability to use "haxelib git" check if your path allows haxelib

**Comment by F1mpo** [comment]
ok, i just didn't had GIT command

**Comment by F1mpo** [comment]
![fixed](https://github.com/user-attachments/assets/f69b7ce1-6b7b-4497-82e2-cce958ac759d)
forgot to send immage
