### ISSUE TITLE
(QUESTION)where do i need to add changes

### ISSUE THREAD

**Issue by F1mpo** [TheZoroForce240/FNF-Modcharting-Tools#74]
i know i really stupid i guess but if there was a patch at least its just saying in *"FILE NAME.HX"* (code) I NEED TO CHANGE THAT OR ADD?! AND THERE IS NO SOME FILES!!! ANYWAYS WHAT DOES PROJECT.XML MEAN!!!
![where put this](https://github.com/user-attachments/assets/8c404ac3-612b-4f58-9ab8-5c40d7e87d01)
![where put this2](https://github.com/user-attachments/assets/dfa49a89-4656-422c-8be0-5bffe95182cf)
![where put this3](https://github.com/user-attachments/assets/ebc96bfc-49e1-4ffb-a866-feef1886dcc3)

**Comment by moxie-coder** [comment]
if you don't see that then that means you don't have the source code, and if you don't even know how to code in Haxe, then go learn it with the Haxe Docs

**Comment by F1mpo** [comment]
> if you don't see that then that means you don't have the source code, and if you don't even know how to code in Haxe, then go learn it with the Haxe Docs

ok

**Comment by F1mpo** [comment]
also what about source code
i download git command, paste command from 1st instalation and then i moved on 2nd "list" and in my _C/haxetools/lib/fnf modchart tools/source/modchart_ there was no playstate.hx or something like that

**Comment by F1mpo** [comment]
> if you don't see that then that means you don't have the source code, and if you don't even know how to code in Haxe, then go learn it with the Haxe Docs

oh, i saw original message now check this https://scratch.mit.edu/projects/876170657/ also i have other account

**Comment by moxie-coder** [comment]
> also what about source code i download git command, paste command from 1st instalation and then i moved on 2nd "list" and in my _C/haxetools/lib/fnf modchart tools/source/modchart_ there was no playstate.hx or something like that

download it from here https://github.com/ShadowMario/FNF-PsychEngine

**Comment by F1mpo** [comment]
and i need to put this in *C/haxetools/lib/fnf modchart tools* ?

**Comment by F1mpo** [comment]
> and i need to put this in _C/haxetools/lib/fnf modchart tools_ ?
i mean project.xml and other

**Comment by moxie-coder** [comment]
> and i need to put this in _C/haxetools/lib/fnf modchart tools_ ?

no, just somewhere on your computer

**Comment by F1mpo** [comment]
thank you

**Comment by F1mpo** [comment]
and to edit this i need make script?

**Comment by moxie-coder** [comment]
if you know how to edit the source yeah, but there's wiki if that helps https://github.com/TheZoroForce240/FNF-Modcharting-Tools/wiki

**Comment by F1mpo** [comment]
thanks, i can close now this question
